version: 1
disable_existing_loggers: False

formatters:
  simple:
    format: "%(asctime)s | %(levelname)s | %(filename)s --> %(message)s"
  verbose:
    format: "%(asctime)s | %(levelname)s | %(module)s : %(filename)s : %(lineno)d --> %(message)s"
  consumer:
    format: "%(asctime)s | %(threadName)s | %(filename)s:%(lineno)d | %(levelname)s : %(message)s"

handlers:
  errorHandler:
    class: logging.handlers.TimedRotatingFileHandler
    filename: /data/log/discuzx-tools/error.log
    when: midnight
    backupCount: 30
    formatter: verbose
    encoding: utf8

  consoleHandler:
    class: logging.StreamHandler
    formatter: consumer
    level: INFO
    stream: ext://sys.stdout

  stderrHandler:
    class: logging.StreamHandler
    formatter: consumer
    level: ERROR
    stream: ext://sys.stderr

  infoHandler:
    class: logging.handlers.TimedRotatingFileHandler
    filename: /data/log/discuzx-tools/info.log
    when: midnight
    backupCount: 30
    formatter: simple
    encoding: utf8

loggers:
  web_service:
    handlers: [errorHandler, consoleHandler, infoHandler]
    level: INFO
    propagate: True

  crons_consumer:
    handlers: [consoleHandler, stderrHandler]
    level: INFO
    propagate: True